Raise exception when no workflows are returned
E.g. if GitHub API returns an error (due to rate limit breach, or
lack of permissions on the token) then there won't be a
`workflow_runs` property on the JSON response.

Previously, such cases would unhelpfully fail with:

```
`ci_workflow_run_id': undefined method `find' for nil:NilClass (NoMethodError)
    ci_workflow = ci_workflow_api_response["workflow_runs"].find { |run| run["name"] == "CI" }
                                                           ^^^^^
```

At least now, we can see exactly what the `ci_workflow_api_response`
is.