Catch exception when Rubygem does not exist
This should fix errors such as:
/home/runner/work/govuk-dependabot-merger/govuk-dependabot-merger/lib/change_set.rb:5:in `internal?': undefined method `any?' for an instance of String (NoMethodError)
      .any? { |owner| owner["handle"] == "govuk" }